class Provinces {
  static final List<String> thaiProvinces = <String>[
    "All",
    "Bangkok",
    "Samut Prakan",
    "Nonthaburi",
    "Pathum Thani",
    "Phra Nakhon Si Ayutthaya",
    "Ang Thong",
    "Lopburi",
    "Sing Buri",
    "Chai Nat",
    "Nakhon Nayok",
    "Sa Kaeo",
    "Prachin Buri",
    "Chachoengsao",
    "Chon Buri",
    "Rayong",
    "Chanthaburi",
    "Trat",
    "Kanchanaburi",
    "Suphan Buri",
    "Ratchaburi",
    "Nakhon Pathom",
    "Samut Sakhon",
    "Samut Songkhram",
    "Phetchaburi",
    "Prachuap Khiri Khan",
    "Chumphon",
    "Ranong",
    "Surat Thani",
    "Phang Nga",
    "Phuket",
    "Krabi",
    "Nakhon Si Thammarat",
    "Trang",
    "Phatthalung",
    "Satun",
    "Songkhla",
    "Yala",
    "Pattani",
    "Narathiwat",
    "Uthai Thani",
    "Kamphaeng Phet",
    "Tak",
    "Sukhothai",
    "Phitsanulok",
    "Phichit",
    "Phetchabun",
    "Roi Et",
    "Maha Sarakham",
    "Kalasin",
    "Khon Kaen",
    "Chaiyaphum",
    "Nakhon Ratchasima",
    "Buriram",
    "Surin",
    "Sisaket",
    "Ubon Ratchathani",
    "Amnat Charoen",
    "Nong Bua Lam Phu",
    "Bueng Kan",
    "Nong Khai",
    "Loei",
    "Sakon Nakhon",
    "Nakhon Phanom",
    "Mukdahan",
    "Chiang Mai",
    "Lamphun",
    "Lampang",
    "Uttaradit",
    "Phrae",
    "Nan",
    "Phayao",
    "Chiang Rai",
    "Mae Hong Son"
  ];
  static final List<String> thaiProvincesnoAll = <String>[
    "Bangkok",
    "Samut Prakan",
    "Nonthaburi",
    "Pathum Thani",
    "Phra Nakhon Si Ayutthaya",
    "Ang Thong",
    "Lopburi",
    "Sing Buri",
    "Chai Nat",
    "Nakhon Nayok",
    "Sa Kaeo",
    "Prachin Buri",
    "Chachoengsao",
    "Chon Buri",
    "Rayong",
    "Chanthaburi",
    "Trat",
    "Kanchanaburi",
    "Suphan Buri",
    "Ratchaburi",
    "Nakhon Pathom",
    "Samut Sakhon",
    "Samut Songkhram",
    "Phetchaburi",
    "Prachuap Khiri Khan",
    "Chumphon",
    "Ranong",
    "Surat Thani",
    "Phang Nga",
    "Phuket",
    "Krabi",
    "Nakhon Si Thammarat",
    "Trang",
    "Phatthalung",
    "Satun",
    "Songkhla",
    "Yala",
    "Pattani",
    "Narathiwat",
    "Uthai Thani",
    "Kamphaeng Phet",
    "Tak",
    "Sukhothai",
    "Phitsanulok",
    "Phichit",
    "Phetchabun",
    "Roi Et",
    "Maha Sarakham",
    "Kalasin",
    "Khon Kaen",
    "Chaiyaphum",
    "Nakhon Ratchasima",
    "Buriram",
    "Surin",
    "Sisaket",
    "Ubon Ratchathani",
    "Amnat Charoen",
    "Nong Bua Lam Phu",
    "Bueng Kan",
    "Nong Khai",
    "Loei",
    "Sakon Nakhon",
    "Nakhon Phanom",
    "Mukdahan",
    "Chiang Mai",
    "Lamphun",
    "Lampang",
    "Uttaradit",
    "Phrae",
    "Nan",
    "Phayao",
    "Chiang Rai",
    "Mae Hong Son"
  ];
  getproviceslist() {
    return thaiProvinces;
  }

  getproviceslistnoall() {
    return thaiProvincesnoAll;
  }
}
